namespace Chatcheology.Data.Workspace
{
    /// <summary>
    /// What one successful workspace import created.
    /// </summary>
    /// <remarks>
    /// Returned so the caller does not have to query the database back to find out which rows its
    /// own import produced. It exists only because those identifiers are generated by SQLite and
    /// are otherwise unobservable.
    /// </remarks>
    public sealed class WorkspaceImportResult
    {
        /// <summary>The generated <c>ImportSource.ImportSourceID</c>.</summary>
        public required long ImportSourceID { get; init; }

        /// <summary>The generated <c>Conversation.ConversationID</c>.</summary>
        public required long ConversationID { get; init; }

        /// <summary>How many distinct participants this import created.</summary>
        public required int ParticipantCount { get; init; }

        /// <summary>How many messages this import stored.</summary>
        public required int MessageCount { get; init; }
    }
}
